FROM ${IMAGE_NAME}:latest
MAINTAINER harlo <harlo.holmes@gmail.com>

ADD src/install.sh /home/${USER}/install.sh
ADD src/run.sh /home/${USER}/run.sh
ADD src/startup.sh /home/${USER}/startup.sh
ADD src/update.sh /home/${USER}/update.sh

RUN sudo chown -R ${USER}:${USER} /home/${USER}
RUN chmod +x /home/${USER}/*.sh